### ISSUE TITLE
ssh_username must be specified

### ISSUE THREAD

**Issue by fstab** [m110/packer-builder-hcloud#2]
When running `packer build` I get the following error:

```
1 error(s) occurred:

* An ssh_username must be specified
  Note: some builders used to default ssh_username to "root".
```

It's very easy to fix: Just add `"ssh_username": "root"` to the builder configuration and it works.

It would be good if you could either add this to the configuration example in README.md, or implement it as a default that you don't need to configure it.

Thanks for the packer builder!!!

**Comment by m110** [comment]
Hey @fstab, thanks for pointing that out. I'm not sure if adding a default value is considered best practice, so I've updated the example config as for now. :)

**Comment by yaffol** [comment]
Just a note to say that I have run into this - while adapting the packer getting started instructions from aws to hcloud - it took me a couple of tries to work out that I needed to add `"ssh_username": "root"` to the configuration.
Having it listed in the example config, but not as an option in the docs just above that (and an option which you cannot change at that..) is quite confusing.

I was wondering if there were situations where I would want to use another user - I'm inclined to avoid root by instinct, but perhaps it's OK for provisioning only?

**Comment by masilver004** [comment]
I realize this post is several years old, however, I ran into this issue this morning building a Windows Server Image.   

It looks like SSH is the default communication method, therefore if you are using it, as others have stated, adding "ssh_username" to your build will resolve.  A second option is to define COMMUNICATOR to "winrm" (what's being used in my case) then it doesn't look for SSH creds.
